{% set version = "0.22.0" %}

package:
  name: scikit-rf
  version: {{ version }}


source:
  fn: scikit-rf-{{ version }}.zip
  url: https://github.com/scikit-rf/scikit-rf/archive/v{{ version }}.zip
  sha256: 4e998da229fb89bdd3df62e35ed12f540525f06f2887b48bf8ed207c0cd509c8



build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib-base
    - six
    - future
    - qtpy
    - pyyaml
    - pyqtgraph
    - pyvisa
    - sip
    - traits
    - bokeh
    - traitsui

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media

about:
  home: http://www.scikit-rf.org
  license: BSD-3-Clause
  summary: Object Oriented Microwave Engineering.
  doc_url: http://scikit-rf.readthedocs.io/
  dev_url: https://github.com/scikit-rf/scikit-rf
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arsenovic
    - jhillairet
