{% set version = "0.16.0" %}

package:
  name: scikit-rf
  version: {{ version }}


source:
  fn: scikit-rf-{{ version }}.zip
  url: https://github.com/scikit-rf/scikit-rf/archive/{{ version }}.zip
  sha256: 345b6e19c5f2de1cdfc83a665c29b64df4820fcadc476c094d9c12ce251b36d7



build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib-base
    - six
    - future

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media

about:
  home: http://www.scikit-rf.org
  license: BSD 3-Clause
  summary: Object Oriented Microwave Engineering.
  doc_url: http://scikit-rf.readthedocs.io/
  dev_url: https://github.com/scikit-rf/scikit-rf
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arsenovic
    - jhillairet
