{% set version = "0.15" %}

package:
  name: scikit-rf
  version: {{ version }}


source:
  fn: scikit-rf-{{ version }}.zip
  url: https://github.com/scikit-rf/scikit-rf/archive/v{{ version }}.zip
  sha256: 2bc9ed3107234a8034ea7f0757a6d9244406f6fe65ce9a64d426d0e544fc2e63



build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib
    - six
    - future

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media

about:
  home: http://www.scikit-rf.org
  license: BSD 3-Clause
  summary: 'Object Oriented Microwave Engineering.'
  doc_url: http://scikit-rf.readthedocs.io/
  dev_url: https://github.com/scikit-rf/scikit-rf
  license_file: LICENSE.txt
  
extra:
  recipe-maintainers:
    - arsenovic
